webtalk_init -webtalk_dir /home/24CAP1G13/CA_Assignment_2/CA_Assignment_2.sim/sim_1/behav/xsim/xsim.dir/TOP_MODULE_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 26 22:44:35 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211392236_1777568676_210755782_703" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3da3bc14-bd35-417b-b8f0-72c2dcd793d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb0985aec552461dab8b8ba953eeac04" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "n/a" -context "user_environment"
webtalk_add_data -client project -key os_release -value "NAME="Red Hat Enterprise Linux Server"" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7542 32-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "20" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "58 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "74" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "20" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.59_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "413652_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3194651518 -regid "211392236_1777568676_210755782_703" -xml /home/24CAP1G13/CA_Assignment_2/CA_Assignment_2.sim/sim_1/behav/xsim/xsim.dir/TOP_MODULE_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/24CAP1G13/CA_Assignment_2/CA_Assignment_2.sim/sim_1/behav/xsim/xsim.dir/TOP_MODULE_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/24CAP1G13/CA_Assignment_2/CA_Assignment_2.sim/sim_1/behav/xsim/xsim.dir/TOP_MODULE_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
